// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleApp.Entities;

#nullable disable

namespace SimpleApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleApp.Entities.ComCustomer", b =>
                {
                    b.Property<int>("ComCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COM_CUSTOMER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComCustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.HasKey("ComCustomerId");

                    b.ToTable("COM_CUSTOMER", (string)null);

                    b.HasData(
                        new
                        {
                            ComCustomerId = 1,
                            CustomerName = "Alpha"
                        },
                        new
                        {
                            ComCustomerId = 2,
                            CustomerName = "Beta"
                        },
                        new
                        {
                            ComCustomerId = 3,
                            CustomerName = "Gamma"
                        });
                });

            modelBuilder.Entity("SimpleApp.Entities.SoItem", b =>
                {
                    b.Property<int>("SoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SO_ITEM_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoItemId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("PRICE");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("SoOrderId")
                        .HasColumnType("int")
                        .HasColumnName("SO_ORDER_ID");

                    b.HasKey("SoItemId");

                    b.HasIndex("SoOrderId");

                    b.ToTable("SO_ITEM", (string)null);

                    b.HasData(
                        new
                        {
                            SoItemId = 1,
                            ItemName = "Kursi",
                            Price = 50000,
                            Quantity = 10,
                            SoOrderId = 1
                        },
                        new
                        {
                            SoItemId = 2,
                            ItemName = "Meja",
                            Price = 100000,
                            Quantity = 5,
                            SoOrderId = 1
                        },
                        new
                        {
                            SoItemId = 3,
                            ItemName = "Tabung Gas",
                            Price = 25000,
                            Quantity = 8,
                            SoOrderId = 2
                        },
                        new
                        {
                            SoItemId = 4,
                            ItemName = "Kompor Gas",
                            Price = 200000,
                            Quantity = 3,
                            SoOrderId = 2
                        },
                        new
                        {
                            SoItemId = 5,
                            ItemName = "Jendela",
                            Price = 500000,
                            Quantity = 3,
                            SoOrderId = 3
                        },
                        new
                        {
                            SoItemId = 6,
                            ItemName = "Pintu",
                            Price = 100000,
                            Quantity = 10,
                            SoOrderId = 4
                        },
                        new
                        {
                            SoItemId = 7,
                            ItemName = "Monitor",
                            Price = 1000000,
                            Quantity = 2,
                            SoOrderId = 5
                        },
                        new
                        {
                            SoItemId = 8,
                            ItemName = "AC",
                            Price = 900000,
                            Quantity = 5,
                            SoOrderId = 6
                        });
                });

            modelBuilder.Entity("SimpleApp.Entities.SoOrder", b =>
                {
                    b.Property<int>("SoOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SO_ORDER_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoOrderId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS");

                    b.Property<int>("ComCustomerId")
                        .HasColumnType("int")
                        .HasColumnName("COM_CUSTOMER_ID");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ORDER_DATE");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ORDER_NO");

                    b.HasKey("SoOrderId");

                    b.HasIndex("ComCustomerId");

                    b.ToTable("SO_ORDER", (string)null);

                    b.HasData(
                        new
                        {
                            SoOrderId = 1,
                            Address = "Jl Nangka",
                            ComCustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5868),
                            OrderNo = "Order-1001"
                        },
                        new
                        {
                            SoOrderId = 2,
                            Address = "Jl Kampung Rambutan",
                            ComCustomerId = 1,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5877),
                            OrderNo = "Order-1002"
                        },
                        new
                        {
                            SoOrderId = 3,
                            Address = "Jl Pabuaran",
                            ComCustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5879),
                            OrderNo = "Order-1003"
                        },
                        new
                        {
                            SoOrderId = 4,
                            Address = "Jl Kepandaian",
                            ComCustomerId = 2,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5880),
                            OrderNo = "Order-1004"
                        },
                        new
                        {
                            SoOrderId = 5,
                            Address = "Jl Pasuruan",
                            ComCustomerId = 3,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5881),
                            OrderNo = "Order-1005"
                        },
                        new
                        {
                            SoOrderId = 6,
                            Address = "Jl Gajah",
                            ComCustomerId = 3,
                            OrderDate = new DateTime(2025, 3, 27, 5, 43, 46, 57, DateTimeKind.Local).AddTicks(5883),
                            OrderNo = "Order-1006"
                        });
                });

            modelBuilder.Entity("SimpleApp.Entities.SoItem", b =>
                {
                    b.HasOne("SimpleApp.Entities.SoOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("SoOrderId")
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SimpleApp.Entities.SoOrder", b =>
                {
                    b.HasOne("SimpleApp.Entities.ComCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("ComCustomerId")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SimpleApp.Entities.ComCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SimpleApp.Entities.SoOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
